version: 2.1
executors:
  node:
    docker:
    - image: circleci/node
jobs:
  frontend_install:
    executor: node
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - persist_to_workspace:
          paths:
          - frontend/
          root: ~/project
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
  frontend_build:
    executor: node
    working_directory: ~/project/frontend/
    steps:
      - run: find ./ | grep -v "node_modules"
      - attach_workspace:
          at: ~/project/
      - run: find ./ | grep -v "node_modules"
      - run: yarn build
      # https://circleci.com/docs/2.0/configuration-reference/#store_artifacts
      - store_artifacts:
          path: ./build
  
workflows:
  version: 2
  push:
    jobs:
    - frontend_install
    - frontend_build:
        requires:
          - frontend_install